// Mocks generated by Mockito 5.4.6 from annotations
// in slice/test/media_EncDec_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:typed_data' as _i4;

import 'package:encrypt/encrypt.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:slice/services/encryption%20_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeKey_0 extends _i1.SmartFake implements _i2.Key {
  _FakeKey_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EncryptService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptService extends _i1.Mock implements _i3.EncryptService {
  MockEncryptService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Key get key =>
      (super.noSuchMethod(
            Invocation.getter(#key),
            returnValue: _FakeKey_0(this, Invocation.getter(#key)),
          )
          as _i2.Key);

  @override
  _i4.Uint8List encryptBytes(_i4.Uint8List? data) =>
      (super.noSuchMethod(
            Invocation.method(#encryptBytes, [data]),
            returnValue: _i4.Uint8List(0),
          )
          as _i4.Uint8List);

  @override
  _i4.Uint8List decryptBytes(_i4.Uint8List? encryptedData) =>
      (super.noSuchMethod(
            Invocation.method(#decryptBytes, [encryptedData]),
            returnValue: _i4.Uint8List(0),
          )
          as _i4.Uint8List);
}
