// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF0brcfJaMpAl-PEV9RHjPkmIc-jNqjeg',
    appId: '1:347217023381:web:0579de53db13c2e115269c',
    messagingSenderId: '347217023381',
    projectId: 'slice-37ec8',
    authDomain: 'slice-37ec8.firebaseapp.com',
    storageBucket: 'slice-37ec8.firebasestorage.app',
    measurementId: 'G-L1GY4HZDXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABKvlVjauXHhFKOc8p__ulz2Fi8Mx9LlM',
    appId: '1:347217023381:android:79b01a779881e05115269c',
    messagingSenderId: '347217023381',
    projectId: 'slice-37ec8',
    storageBucket: 'slice-37ec8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuiBY0uxlgpl-afxvCrR2Sh6iU3WCXwV0',
    appId: '1:347217023381:ios:20ffb397b4c1146d15269c',
    messagingSenderId: '347217023381',
    projectId: 'slice-37ec8',
    storageBucket: 'slice-37ec8.firebasestorage.app',
    iosBundleId: 'com.example.slice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuiBY0uxlgpl-afxvCrR2Sh6iU3WCXwV0',
    appId: '1:347217023381:ios:20ffb397b4c1146d15269c',
    messagingSenderId: '347217023381',
    projectId: 'slice-37ec8',
    storageBucket: 'slice-37ec8.firebasestorage.app',
    iosBundleId: 'com.example.slice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF0brcfJaMpAl-PEV9RHjPkmIc-jNqjeg',
    appId: '1:347217023381:web:51a7315a1037071c15269c',
    messagingSenderId: '347217023381',
    projectId: 'slice-37ec8',
    authDomain: 'slice-37ec8.firebaseapp.com',
    storageBucket: 'slice-37ec8.firebasestorage.app',
    measurementId: 'G-RFQS5P4BLC',
  );

}
